#!/usr/bin/env bash
set -eo pipefail
xxd -i template.yrg > more/template.h
gcc main.c jorkdir/*.c cwalk/src/*.c more/*.c -Icwalk/include -Imore -Ijorkdir -lbinaryen -lreadline -o yargine.x86_64 -O3
[ -z "$1" ] && ./yargine.x86_64
rm more/template.h