#!/usr/bin/env bash
set -eo pipefail
CWD="$(pwd)"
DIR=~/Documents/yargTesting/ # change to . if you don't want cd
[ ! -f yargine.x86_64 ] && ./build no
cp -r appimage/. yargine.AppDir/
mv yargine.x86_64 yargine.AppDir/yargine # sacrifice the yargine for the appdir...
ldd yargine.AppDir/yargine | sed -n "s/.* => \(.*\) .*/\1/p" | while read -r l; do
	mkdir -p "yargine.AppDir/$(dirname "$l")"
	cp "$l" "yargine.AppDir/$l"
done
appimagetool yargine.AppDir yargine.AppImage #> /dev/null 2>&1 # silence your logs at last
rm -rf yargine.AppDir
[ -z "$1" ] && cd $DIR && $CWD/yargine.AppImage && cd $CWD