name: build deb

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: build
              run: |
                  git submodule update --init --recursive
                  aria2c "https://github.com/WebAssembly/binaryen/releases/download/version_125/binaryen-version_125-x86_64-linux.tar.gz" -j 16 -x 16 -s 16
                  sudo tar --strip-components=1 -xzf binaryen-version_125-x86_64-linux.tar.gz -C /usr/local/
                  sudo apt install libreadline-dev libreadline8t64 readline-common devscripts debhelper-compat
                  debuild -uc -us
            - uses: actions/upload-artifact@v6.0.0
              with:
                  path: ../yargine*.deb